# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class F1viewer < Formula
  desc "TUI client for F1TV"
  homepage "https://github.com/SoMuchForSubtlety/f1viewer/"
  version "1.5.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/SoMuchForSubtlety/f1viewer/releases/download/v1.5.0/f1viewer_1.5.0_macOS_amd64.tar.gz"
    sha256 "f891bff22060f8da8421952309006dafc56123397b8fa36a24f204620a1b2e64"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/SoMuchForSubtlety/f1viewer/releases/download/v1.5.0/f1viewer_1.5.0_macOS_arm64.tar.gz"
    sha256 "b90a42d930cef44ffa6c25220dea44996cc53dad10fdb15786994d8184aa69cb"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/SoMuchForSubtlety/f1viewer/releases/download/v1.5.0/f1viewer_1.5.0_linux_amd64.tar.gz"
    sha256 "d587b03712f847a18a1d1ca585af794a1dc6c0d80bf950833ade3029910c459c"
  end

  def install
    bin.install "f1viewer"
  end
end
