# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class F1viewer < Formula
  desc "TUI client for F1TV"
  homepage "https://github.com/SoMuchForSubtlety/f1viewer/"
  version "2.0.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/SoMuchForSubtlety/f1viewer/releases/download/v2.0.1/f1viewer_2.0.1_macOS_amd64.tar.gz"
    sha256 "2ba827f167de43ed3937629469782bbcb1fe336b075d0cbb5c7a25a544bf4018"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/SoMuchForSubtlety/f1viewer/releases/download/v2.0.1/f1viewer_2.0.1_macOS_arm64.tar.gz"
    sha256 "ff85db7d75ef122c8440441be998d8add104c5408090a34da7db14a6c14e181c"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/SoMuchForSubtlety/f1viewer/releases/download/v2.0.1/f1viewer_2.0.1_linux_amd64.tar.gz"
    sha256 "c9eca1498fa9e57b5a5b24f485e82d41253c83bf5728bce496e316cce2ccd743"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/SoMuchForSubtlety/f1viewer/releases/download/v2.0.1/f1viewer_2.0.1_linux_armv6.tar.gz"
    sha256 "b5a33551216c152a6ec3d03ad71e7c2d4909211ce0fbd25b696c029a757350c5"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/SoMuchForSubtlety/f1viewer/releases/download/v2.0.1/f1viewer_2.0.1_linux_arm64.tar.gz"
    sha256 "1fdf686bee6df343ee7cc4a39c7b02ecaee9644ec217246f98d624ee4078912d"
  end

  def install
    bin.install "f1viewer"
  end
end
