# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class F1viewer < Formula
  desc "TUI client for F1TV"
  homepage "https://github.com/SoMuchForSubtlety/f1viewer/"
  version "2.7.0"

  on_macos do
    url "https://github.com/SoMuchForSubtlety/f1viewer/releases/download/v2.7.0/f1viewer_2.7.0_macOS_all.tar.gz"
    sha256 "f461ddb1836fe60be44f041fc05499d7aafddfe9edfa063fbdb2a652399fd1bf"

    def install
      bin.install "f1viewer"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SoMuchForSubtlety/f1viewer/releases/download/v2.7.0/f1viewer_2.7.0_linux_arm64.tar.gz"
      sha256 "bf42aa456714ef88e246adcc9fccebc6b61dfa8f94ee6acc1b2fbbb46c8da5fe"

      def install
        bin.install "f1viewer"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/SoMuchForSubtlety/f1viewer/releases/download/v2.7.0/f1viewer_2.7.0_linux_armv6.tar.gz"
      sha256 "3ffff17f193113477095f67bcb9841709cc8fa039417d67b8547cce00597ad53"

      def install
        bin.install "f1viewer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SoMuchForSubtlety/f1viewer/releases/download/v2.7.0/f1viewer_2.7.0_linux_amd64.tar.gz"
      sha256 "098cdd77628fdf9aa26c2c54511981c4d25f6b2030983952b4b9244e02f2c579"

      def install
        bin.install "f1viewer"
      end
    end
  end
end
